site_name: My example site
site_author: NORCE
site_url: https://mydomain.org/mysite
repo_url: https://github.com/patnr/mkdocs2
edit_uri: edit/main/docs/

docs_dir: docs
# nav:
#   - Home: index.md
#   - Other: other_page.md
#   - Reference: reference/

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil 
    view: material/eye
  features:
    - content.code.copy # copy button
    # - content.code.select # [insiders only]
    - content.code.annotate # clickable toggler for code comments
    - navigation.indexes # enable subdir/index.md
    - toc.follow # ?
    # - toc.integrate # render ToC as part of left sidebar [not compat with navigation.indexes]
    - navigation.tabs # top-level sections rendered in header tabs (for wide screens) instead of left sidebar
    # - navigation.tabs.sticky # don't hide tabs when scrolled
    # - navigation.expand # expand sections
    # - navigation.sections # group (rather than collapse) top-level sections 
    - navigation.path # breadcrumbs
    # - navigation.prune # for large projects
    - navigation.tracking # update URL to current section
    - navigation.footer # "Next/Prev"
    - navigation.instant # SSA
    - navigation.instant.progress # Progbar on top
    - navigation.top # "back to top when scrolling up"
    - header.autohide
    - search.highlight # highlight matches on page
    - search.share # deep link to search
    - search.suggest # search suggestions

  custom_dir: overrides

plugins:
  - glightbox # zoom functionality
  # - roamlinks
  # - blog
  - search
  - autorefs # enable anchor/heading links without specifying its page

  # Autodoc from docstrings:
  - gen-files: # Genrate .md reflecting .py hierarchy:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav: # Auto-generate nav
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings: # Parse docstrings
      handlers:
        python:
          paths: [., example]
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv

# Mostly from
# https://squidfunk.github.io/mkdocs-material/setup/extensions/#recommended-configuration
markdown_extensions:
  # Python Markdown official extensions
  - abbr
  - admonition
  - def_list
  - footnotes
  - toc:
      title: On this page
      permalink: ⚓︎
      toc_depth: 3
  # Adds the ability to align images, add captions to images (rendering them as figures), and mark large images for lazy-loading:
  - attr_list
  - md_in_html

  # Extensions part of Pymdown
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

hooks:
  - list_logos.py

extra_javascript:
  - javascripts/extra.js
  # For MathJax
  - javascripts/mathjax.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra_css:
  - stylesheets/code_select.css


extra:
  generator: false # "Made with Material for MkDocs"
  footer:
    logos:
      row1:
        - name: norce.svg
          height: 50px
          brightness: 50%
        - name: nfr.svg
          height: 80px
          brightness: 50%
      row2:
        - name: akerbp.svg
          height: 40px
          brightness: 50%
        - name: equinor.svg
          height: 60px
          brightness: 50%
        - name: wintershall-dea.svg
          height: 80px
          brightness: 70%
