site_name: My example site
site_url: https://mydomain.org/mysite
# edit_uri: blob/master/docs/
# nav:
#   - Home: index.md
#   - Other: other_page.md
#   - Reference: reference/

theme:
  name: material
  features:
    - content.code.copy
    # - content.code.select # insiders only
    - content.code.annotate

plugins:
  - glightbox
  # - roamlinks
  # - blog
  - search
  - autorefs

  # Autodoc from docstrings:
  - gen-files: # Genrate .md reflecting .py hierarchy:
      scripts:
        - scripts/gen_ref_pages.py
  - literate-nav: # Auto-generate nav
      nav_file: SUMMARY.md
  - section-index
  - mkdocstrings: # Extract docstrings
      handlers:
        python:
          paths: [., example]
          import:
            - https://docs.python.org/3/objects.inv
            - https://mkdocstrings.github.io/objects.inv

# Mostly from
# https://squidfunk.github.io/mkdocs-material/setup/extensions/#recommended-configuration
markdown_extensions:
  # Python Markdown official extensions
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true

  # Extensions part of Pymdown
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
