[project]
name = "example"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "mkdocs-material>=9.5.42",
    "mkdocstrings-python>=1.12.2",
]
